services:
  app:
    entrypoint:
      - sleep
      - infinity
    image: remixdev
    build:
      dockerfile: Dockerfile
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
